version: '3'

services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${9090:-9090}:9090"
    volumes:
      - "${/root/linkding:-./data}:/etc/linkding/data"
    env_file:
      - .env
    restart: unless-stopped
